CREATE TABLE IF NOT EXISTS tripay_product (
  id serial PRIMARY KEY,
  kind text NOT NULL,
  category_id integer,
  category_name text,
  operator_id integer,
  operator_name text,
  product_code text NOT NULL UNIQUE,
  product_name text NOT NULL,
  harga_modal integer NOT NULL,
  margin_flat integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  tripay_status integer NOT NULL DEFAULT 1,
  raw_data jsonb,
  synced_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tripay_transaction (
  id serial PRIMARY KEY,
  reference text NOT NULL UNIQUE,
  tripay_trx_id integer,
  warga_id integer NOT NULL REFERENCES warga(id),
  rwcoin_transaksi_id integer NOT NULL REFERENCES rwcoin_transaksi(id),
  refunded_rwcoin_transaksi_id integer REFERENCES rwcoin_transaksi(id),
  product_id integer REFERENCES tripay_product(id),
  kind text NOT NULL,
  product_code text NOT NULL,
  product_name text NOT NULL,
  target text NOT NULL,
  no_meter_pln text,
  harga_modal integer NOT NULL,
  margin_flat integer NOT NULL DEFAULT 0,
  harga_jual integer NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  tripay_status integer NOT NULL DEFAULT 0,
  note text,
  serial_number text,
  request_payload jsonb,
  response_payload jsonb,
  callback_payload jsonb,
  success_at timestamp,
  failed_at timestamp,
  refunded_at timestamp,
  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now()
);
