ALTER TABLE warga
  ADD COLUMN IF NOT EXISTS no_kk_di_ktp text,
  ADD COLUMN IF NOT EXISTS nama_alias text,
  ADD COLUMN IF NOT EXISTS nomor_whatsapp_alternatif text,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS golongan_darah text,
  ADD COLUMN IF NOT EXISTS kewarganegaraan text NOT NULL DEFAULT 'WNI',
  ADD COLUMN IF NOT EXISTS suku text,
  ADD COLUMN IF NOT EXISTS status_ektp text,
  ADD COLUMN IF NOT EXISTS no_akta_lahir text,
  ADD COLUMN IF NOT EXISTS punya_akta_lahir boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS punya_kia boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS punya_npwp boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS punya_sim boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS jenis_sim text,
  ADD COLUMN IF NOT EXISTS punya_paspor boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS alamat_domisili text,
  ADD COLUMN IF NOT EXISTS lama_tinggal_tahun integer,
  ADD COLUMN IF NOT EXISTS status_tinggal_individu text,
  ADD COLUMN IF NOT EXISTS hubungan_dengan_pemilik_rumah text,
  ADD COLUMN IF NOT EXISTS nama_kontak_darurat text,
  ADD COLUMN IF NOT EXISTS hubungan_kontak_darurat text,
  ADD COLUMN IF NOT EXISTS nomor_kontak_darurat text,
  ADD COLUMN IF NOT EXISTS sedang_sekolah boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS nama_sekolah text,
  ADD COLUMN IF NOT EXISTS jenjang_sekolah text,
  ADD COLUMN IF NOT EXISTS kelas text,
  ADD COLUMN IF NOT EXISTS jurusan text,
  ADD COLUMN IF NOT EXISTS sedang_kuliah boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS nama_kampus text,
  ADD COLUMN IF NOT EXISTS semester text,
  ADD COLUMN IF NOT EXISTS keahlian text,
  ADD COLUMN IF NOT EXISTS status_pekerjaan text,
  ADD COLUMN IF NOT EXISTS nama_tempat_kerja text,
  ADD COLUMN IF NOT EXISTS alamat_tempat_kerja text,
  ADD COLUMN IF NOT EXISTS penghasilan_pribadi text,
  ADD COLUMN IF NOT EXISTS sumber_penghasilan text,
  ADD COLUMN IF NOT EXISTS punya_usaha boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS nama_usaha text,
  ADD COLUMN IF NOT EXISTS punya_bpjs_kesehatan boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS nomor_bpjs_kesehatan text,
  ADD COLUMN IF NOT EXISTS punya_penyakit_kronis boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS penyakit_kronis text,
  ADD COLUMN IF NOT EXISTS alergi text,
  ADD COLUMN IF NOT EXISTS riwayat_rawat_inap text,
  ADD COLUMN IF NOT EXISTS butuh_pendampingan_kesehatan boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS status_bansos_individu text,
  ADD COLUMN IF NOT EXISTS jenis_bansos_individu text,
  ADD COLUMN IF NOT EXISTS lansia boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS anak_yatim_piatu boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS perlu_bantuan_khusus boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS catatan_kerentanan text,
  ADD COLUMN IF NOT EXISTS aktif_kegiatan_rw boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS bidang_partisipasi text,
  ADD COLUMN IF NOT EXISTS jabatan_komunitas text,
  ADD COLUMN IF NOT EXISTS punya_kendaraan boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS jenis_kendaraan text,
  ADD COLUMN IF NOT EXISTS jumlah_kendaraan integer,
  ADD COLUMN IF NOT EXISTS status_verifikasi_data text NOT NULL DEFAULT 'Belum Diverifikasi',
  ADD COLUMN IF NOT EXISTS tanggal_verifikasi_data text,
  ADD COLUMN IF NOT EXISTS catatan_verifikasi text;
